version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "18:00"
      timezone: "Asia/Shanghai"
    allow:
      - dependency-name: "golang.org/*"
      - dependency-name: "github.com/golangci/golangci-lint"
    open-pull-requests-limit: 2
  - package-ecosystem: "gomod"
    directory: "/parser"
    schedule:
      interval: "weekly"
