# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


[[constraint]]
  branch = "master"
  name = "github.com/BurntSushi/toml"

[[constraint]]
  branch = "master"
  name = "github.com/blacktear23/go-proxyprotocol"

[[constraint]]
  name = "github.com/coreos/etcd"
  version = "3.2.6"

[[constraint]]
  branch = "master"
  name = "github.com/coreos/gofail"

[[constraint]]
  branch = "master"
  name = "github.com/cznic/parser"

[[constraint]]
  branch = "master"
  name = "github.com/cznic/sortutil"

[[constraint]]
  branch = "master"
  name = "github.com/google/btree"

[[constraint]]
  name = "github.com/grpc-ecosystem/go-grpc-prometheus"
  version = "1.1.0"

[[constraint]]
  branch = "master"
  name = "github.com/ngaut/pools"

[[constraint]]
  name = "github.com/opentracing/opentracing-go"
  version = "^1.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/pingcap/check"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "0.8.0"

[[override]]
  name = "github.com/sirupsen/logrus"
  revision = "ba1b36c82c5e05c4f912a88eab0dcd91a171688f"

[[constraint]]
  name = "github.com/spaolacci/murmur3"
  version = "1.0.0"

[[constraint]]
  name = "github.com/uber/jaeger-client-go"
  version = "2.8.0"

[[constraint]]
  name = "gopkg.in/natefinch/lumberjack.v2"
  version = "2.0.0"

[[constraint]]
  name = "github.com/pingcap/tipb"
  revision = "07ff5b094233a557a3ac11b1e4d8714d8c6ff406"

[[constraint]]
  name = "github.com/grpc-ecosystem/go-grpc-middleware"
  revision = "82921fcf811d228d2fa202bc31238b356bf9f8d5"
