# Copyright 2021 PingCAP, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

ignoreGeneratedHeader = false
severity = "error"
confidence = 0.8
errorCode = -1
warningCode = -1

[rule.blank-imports]
Exclude = ["~pkg/util/hack/"]
[rule.context-as-argument]
Exclude = ["~pkg/util/hack/"]
[rule.dot-imports]
Exclude = ["~pkg/util/hack/"]
[rule.error-return]
Exclude = ["~pkg/util/hack/"]
[rule.error-strings]
Exclude = ["~pkg/util/hack/"]
[rule.error-naming]
Exclude = ["~pkg/util/hack/"]
[rule.exported]
Exclude = ["~pkg/util/hack/"]
[rule.if-return]
Exclude = ["~pkg/util/hack/"]
[rule.var-naming]
Exclude = ["~pkg/util/hack/"]
[rule.package-comments]
Exclude = ["~pkg/util/hack/"]
[rule.range]
Exclude = ["~pkg/util/hack/"]
#[rule.receiver-naming]
[rule.indent-error-flow]
Exclude = ["~pkg/util/hack/"]
[rule.superfluous-else]
Exclude = ["~pkg/util/hack/"]
[rule.modifies-parameter]
Exclude = ["~pkg/util/hack/"]
[rule.duplicated-imports]
Exclude = ["~pkg/util/hack/"]

# This can be checked by other tools like megacheck
[rule.unreachable-code]
Exclude = ["~pkg/util/hack/"]


# Currently this makes too much noise, but should add it in
# and perhaps ignore it in a few files
#[rule.confusing-naming]
#  severity = "warning"
#[rule.confusing-results]
#  severity = "warning"
#[rule.unused-parameter]
#  severity = "warning"
#[rule.deep-exit]
#  severity = "warning"
#[rule.flag-parameter]
#  severity = "warning"



# Adding these will slow down the linter
# They are already provided by megacheck
# [rule.unexported-return]
# [rule.time-naming]
# [rule.errorf]

# Adding these will slow down the linter
# Not sure if they are already provided by megacheck
# [rule.var-declaration]
# [rule.context-keys-type]
