name: Bazel crossbuild for TiDB/Lightning
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  master:
    name: Bazel Crossbuild Build
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        os:
          - macos
          - ubuntu
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Build Prepare
        uses: ./.github/actions/tidb_build
        with:
          bazelrc: ${{ secrets.BAZELRC }}
          gcp_sa_key: ${{ secrets.GCP_SA_KEY }}
          go-version: 1.25
      - name: Run Build
        shell: bash
        run: |
          #!/bin/bash
          unset CI
          system_name=$(uname -s)
          if [ "$system_name" == "Darwin" ]; then
            sed -i '' '/bazel-cache/d' DEPS.bzl
            sed -i '' '/ats.apps.svc/d' DEPS.bzl
            sed -i '' '/bazel-cache/d' WORKSPACE
            sed -i '' '/ats.apps.svc/d' WORKSPACE
          elif [ "$system_name" == "Linux" ]; then
            sed -i '/bazel-cache/d' DEPS.bzl
            sed -i '/ats.apps.svc/d' DEPS.bzl
            sed -i '/bazel-cache/d' WORKSPACE
            sed -i '/ats.apps.svc/d' WORKSPACE
          fi
          make bazel_bin