name: BR & Lightning 
on:
  push:
    branches:
      - master
    paths:
      - 'br/**'
      - '!**.html'
      - '!**.md'
      - '!CNAME'
      - '!LICENSE'
      - '!br/docs/**'
      - '!br/tests/**'
      - '!br/docker/**'
  pull_request:
    branches:
      - master
    paths:
      - 'br/**'
      - '!**.html'
      - '!**.md'
      - '!CNAME'
      - '!LICENSE'
      - '!br/docs/**'
      - '!br/tests/**'
      - '!br/docker/**'
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# See: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#concurrency.
concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  compile:
    name: Compile for ${{ matrix.os }} / ${{ matrix.target}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest
            target: x86_64-apple-darwin

          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu

          - os: windows-latest
            target: x86_64-pc-windows-msvc
    steps:
      - uses: actions/checkout@v2.1.0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Run build
        run: make build_tools

  compile-freebsd:
    name: Compile for FreeBSD job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Compile for FreeBSD
        run: GOOS=freebsd make build_tools
